language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile!!!"
  - docker build -t mvmaniaz/react-dev -f ./03-react-based/Dockerfile.dev ./03-react-based

script:
  - docker run -e CI=true mvmaniaz/react-dev npm run test -- --coverage

after_success:
  - echo "test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-000140339722"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
