language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t mvmaniaz/react-nodejs-based-front-test -f ./04-react-nodejs-based/front-end/Dockerfile.dev ./04-react-nodejs-based/front-end

script:
  - docker run -e CI=true mvmaniaz/react-nodejs-based-front-test npm run test -- --coverage

after_success:
  - docker build -t mvmaniaz/react-nodejs-based-front ./04-react-nodejs-based/front-end
  - docker build -t mvmaniaz/react-nodejs-based-back ./04-react-nodejs-based/back-end
  - docker build -t mvmaniaz/react-nodejs-based-nginx ./04-react-nodejs-based/nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push mvmaniaz/react-nodejs-based-front
  - docker push mvmaniaz/react-nodejs-based-back
  - docker push mvmaniaz/react-nodejs-based-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "react-nodejs-based"
  env: "ReactNodejsBased-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-000140339722"
  bucket_path: "react-nodejs-based"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
