# docker-compose -p mvmaniaz up -d --build
version: "3.8"
services:
  redis-server:
    container_name: redis-server
    image: redis
    ports:
      - 6379:6379
  compose:
    container_name: app
    build: 
      context: .
      network: host # VirtualBox 에서 실행 할 경우
    ports:
        - 8080:8080
