version: "3.8"
services:
  redis-server:
    container_name: redis-server
    image: redis
    ports:
      - 6379:6379
  compose:
    container_name: compose
    build: 
      context: .
      network: host
    ports:
        - 8080:8080
